/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import Playlist, { PlaylistComponent } from 'react-native-playlist';

const {
  PlaybarSlider,
  PlayPause,
  SkipNext,
  SkipPrev,
  TrackProgress,
  TrackDuration,
  TrackAlbumArt,
  TrackArtist,
  TrackTitle
} = PlaylistComponent

export default class App extends Component<{}> {
  state = {
    switch: false,
    color1: '#111111',
    color2: '#888888'
  }

  async componentDidMount() {
    Playlist.setupPlayer()

    setTimeout(() => {
      this.setState({ 
        switch: false,
        // color1: 'violet',
        // color2: 'orange'
      })
    }, 2000)
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={{ flex: 1, width: '100%' }}>
          <View style={{ flex: 1, backgroundColor: '#e0e0e0' }} />
          <View style={{ flex: 1 }}>
            <PlaybarSlider 
              hasControl={this.state.switch}
              thumbRadius={20}
              trackHeightEnabled={20}
              trackHeightDisabled={10}
              trackPlayedColor={"#444444"}
              // trackRemainingColor={this.state.color2}
              style={{
                backgroundColor: '#f0f0f0',
              }} />
            <View style={{ flexDirection: 'row' }}>
              <TrackProgress style={{ flex: 1, marginLeft: 40, marginRight: -40 }} />
              <SkipPrev style={{ flex: 1}} />
              <PlayPause />
              <SkipNext style={{ flex: 1}}/>
              <TrackDuration style={{ flex: 1 }} />
            </View>
          </View>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
